In [1]:
import pandas as pd

In [2]:
# Load the processed data
print("Loading parquet data...")
df = pd.read_parquet("./tmp/unfv_with_weather_route_29_39.parquet")
print(f"Columns: {df.columns.tolist()}")

Loading parquet data...
Columns: ['route', 'trip_id', 'stopid', 'thrusteet', 'actual_arrival', 'hour', 'day_of_week', 'month', 'day_of_year', 'hour_sin', 'hour_cos', 'day_of_week_sin', 'day_of_week_cos', 'delay_seconds', 'nearest_whole_hour', 'Climate ID', 'Temp (°C)', 'Dew Point Temp (°C)', 'Rel Hum (%)', 'Wind Spd (km/h)', 'Visibility (km)', 'Stn Press (kPa)', 'Precip. Amount (mm)']

In [3]:
df_39 = df[df["route"] == 39]

In [4]:
df_39.dtypes

route                         float64
trip_id                string[python]
stopid                 string[python]
thrusteet              string[python]
actual_arrival         datetime64[ns]
hour                            int32
day_of_week                     int32
month                           int32
day_of_year                     int32
hour_sin                      float64
hour_cos                      float64
day_of_week_sin               float64
day_of_week_cos               float64
delay_seconds                 float64
nearest_whole_hour     datetime64[ns]
Climate ID                    float64
Temp (°C)                     float64
Dew Point Temp (°C)           float64
Rel Hum (%)                   float64
Wind Spd (km/h)               float64
Visibility (km)               float64
Stn Press (kPa)               float64
Precip. Amount (mm)           float64
dtype: object

In [5]:
df_39[df_39.stopid.str.contains("_")].stopid.value_counts().sum()

np.int64(74870)

In [6]:
def create_bound(stopid):
    if "_" in stopid:
        get_bound = stopid.split("_")[1]
        return int(get_bound)
    else:
        return 0

df_39['bound'] = df_39['stopid'].apply(create_bound)

/tmp/ipykernel_57543/412448244.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_39['bound'] = df_39['stopid'].apply(create_bound)

In [7]:
df_39[df_39.stopid.str.contains("_")].bound.value_counts().sum()

np.int64(74870)

In [8]:
df_39['stopid'] = df_39['stopid'].apply(lambda x: int(x.split("_")[0]) if "_" in x else int(x))

/tmp/ipykernel_57543/1285570033.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_39['stopid'] = df_39['stopid'].apply(lambda x: int(x.split("_")[0]) if "_" in x else int(x))

In [9]:
df_39.isna().sum()

route                    0
trip_id                  0
stopid                   0
thrusteet                2
actual_arrival           0
hour                     0
day_of_week              0
month                    0
day_of_year              0
hour_sin                 0
hour_cos                 0
day_of_week_sin          0
day_of_week_cos          0
delay_seconds            0
nearest_whole_hour       0
Climate ID             320
Temp (°C)              320
Dew Point Temp (°C)    320
Rel Hum (%)            320
Wind Spd (km/h)        320
Visibility (km)        320
Stn Press (kPa)        320
Precip. Amount (mm)    320
bound                    0
dtype: int64

In [10]:
df_39_no_na_dropped = df_39.dropna(subset=['Climate ID', 'thrusteet'])

In [11]:
df_39_no_na_dropped.shape

(2153208, 24)

In [12]:
df_39_no_na_dropped.isna().sum()

route                  0
trip_id                0
stopid                 0
thrusteet              0
actual_arrival         0
hour                   0
day_of_week            0
month                  0
day_of_year            0
hour_sin               0
hour_cos               0
day_of_week_sin        0
day_of_week_cos        0
delay_seconds          0
nearest_whole_hour     0
Climate ID             0
Temp (°C)              0
Dew Point Temp (°C)    0
Rel Hum (%)            0
Wind Spd (km/h)        0
Visibility (km)        0
Stn Press (kPa)        0
Precip. Amount (mm)    0
bound                  0
dtype: int64

In [13]:
df_39_no_na_dropped.to_csv("./tmp/df_39_no_na_dropped_without_encoding.csv", index=False)

In [14]:
df_39_no_na_dropped['thrustreet'] = df_39_no_na_dropped['thrusteet']
df_39_no_na_dropped_encoding = pd.get_dummies(df_39_no_na_dropped, columns=['thrusteet'], prefix=['thrusteet'], dtype=int)

/tmp/ipykernel_57543/2406188414.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_39_no_na_dropped['thrustreet'] = df_39_no_na_dropped['thrusteet']

In [15]:
df_39_no_na_dropped_encoding.head(), df_39_no_na_dropped_encoding.shape

(    route    trip_id  stopid          actual_arrival  hour  day_of_week  \
 1    39.0   76911080    8878 2025-01-01 00:07:14.000     0            2
 3    39.0   76911080    8258 2025-01-01 00:07:29.928     0            2
 5    39.0   76911080   10060 2025-01-01 00:07:48.000     0            2
 14   39.0   97485080     938 2025-01-01 00:14:20.169     0            2
 16   39.0  112467080    8878 2025-01-01 00:14:25.000     0            2

     month  day_of_year  hour_sin  hour_cos  ...  thrusteet_Finch Ave West  \
 1       1            1       0.0       1.0  ...                         0
 3       1            1       0.0       1.0  ...                         0
 5       1            1       0.0       1.0  ...                         0
 14      1            1       0.0       1.0  ...                         0
 16      1            1       0.0       1.0  ...                         0

     thrusteet_Finch Station  thrusteet_Gordon Baker Rd  \
 1                         0                          0
 3                         0                          0
 5                         0                          0
 14                        0                          0
 16                        0                          0

    thrusteet_Harold Evans Cres  thrusteet_Littles Rd  thrusteet_McNicoll Ave  \
 1                            0                     0                       0
 3                            0                     0                       0
 5                            0                     0                       0
 14                           0                     0                       0
 16                           0                     0                       0

     thrusteet_Morningview Trail  thrusteet_Neilson Rd  \
 1                             0                     0
 3                             0                     0
 5                             0                     0
 14                            0                     1
 16                            0                     0

     thrusteet_Old Finch Ave  thrusteet_Victoria Park Ave
 1                         0                            0
 3                         0                            0
 5                         0                            0
 14                        0                            0
 16                        0                            0

 [5 rows x 38 columns],
 (2153208, 38))

In [16]:
df_39_no_na_dropped_encoding.to_csv("./tmp/unfv_route_39_no_na_dropped_encoding.csv", index=False)

In [17]:
df_39_no_na_dropped_encoding[(df_39_no_na_dropped_encoding['nearest_whole_hour'] == '2025-01-01 07:00:00') & (df_39_no_na_dropped_encoding['hour'] == 7)][['Temp (°C)', 'actual_arrival', 'delay_seconds']]

      Temp (°C)          actual_arrival  delay_seconds
3360        1.9 2025-01-01 07:00:46.000          9.000
3371        1.9 2025-01-01 07:01:59.409         55.409
3374        1.9 2025-01-01 07:02:22.004         48.004
3380        1.9 2025-01-01 07:02:48.078         45.078
3388        1.9 2025-01-01 07:03:19.108         46.108
...         ...                     ...            ...
3634        1.9 2025-01-01 07:29:05.000        187.000
3638        1.9 2025-01-01 07:29:16.366         16.366
3639        1.9 2025-01-01 07:29:20.725        561.725
3640        1.9 2025-01-01 07:29:33.000        244.000
3643        1.9 2025-01-01 07:29:44.000        559.000

[105 rows x 3 columns]

In [18]:
df_39_no_na_dropped_encoding[(df_39_no_na_dropped_encoding['nearest_whole_hour'] == '2025-01-01 02:00:00') & (df_39_no_na_dropped_encoding['hour'] == 2)][['Temp (°C)', 'actual_arrival', 'delay_seconds']]

     Temp (°C)          actual_arrival  delay_seconds
594        1.4 2025-01-01 02:00:58.000         44.000
598        1.4 2025-01-01 02:01:21.000         43.000
601        1.4 2025-01-01 02:01:30.964         18.964
604        1.4 2025-01-01 02:02:02.813         18.813
606        1.4 2025-01-01 02:02:17.128          5.128
608        1.4 2025-01-01 02:02:28.000         43.000
611        1.4 2025-01-01 02:03:07.587          6.587
616        1.4 2025-01-01 02:03:56.609          5.609
622        1.4 2025-01-01 02:05:21.000         26.000
626        1.4 2025-01-01 02:06:21.000         29.000
628        1.4 2025-01-01 02:06:57.148         18.148
651        1.4 2025-01-01 02:14:09.634         52.634
652        1.4 2025-01-01 02:14:39.926         45.926
655        1.4 2025-01-01 02:15:01.000         29.000
658        1.4 2025-01-01 02:15:17.808         12.808
682        1.4 2025-01-01 02:20:03.000          2.000
688        1.4 2025-01-01 02:21:30.000         34.000
691        1.4 2025-01-01 02:22:36.000         26.000
693        1.4 2025-01-01 02:22:53.899         12.899
698        1.4 2025-01-01 02:23:12.000         52.000
701        1.4 2025-01-01 02:23:30.226         36.226
702        1.4 2025-01-01 02:23:33.000         15.000
705        1.4 2025-01-01 02:23:52.294         23.294
707        1.4 2025-01-01 02:24:17.225         12.225
710        1.4 2025-01-01 02:24:53.157         13.157
712        1.4 2025-01-01 02:25:25.286          2.286

In [19]:
df_39_no_na_dropped_encoding[(df_39_no_na_dropped_encoding['month'] == 1) & (df_39_no_na_dropped_encoding['hour'] == 7)][['Temp (°C)', 'actual_arrival', 'delay_seconds']]

         Temp (°C)          actual_arrival  delay_seconds
3360           1.9 2025-01-01 07:00:46.000          9.000
3371           1.9 2025-01-01 07:01:59.409         55.409
3374           1.9 2025-01-01 07:02:22.004         48.004
3380           1.9 2025-01-01 07:02:48.078         45.078
3388           1.9 2025-01-01 07:03:19.108         46.108
...            ...                     ...            ...
3277514       -0.7 2025-01-31 07:14:59.540         10.540
3277515       -0.7 2025-01-31 07:27:38.000         15.000
3277516       -0.7 2025-01-31 07:28:38.000        386.000
3277517       -0.7 2025-01-31 07:28:50.096         50.096
3277518       -0.7 2025-01-31 07:48:49.000        164.000

[1816 rows x 3 columns]