In [1]:
import pandas as pd

In [2]:
# Load the processed data
print("Loading parquet data...")
df = pd.read_parquet("./tmp/unfv_with_weather_route_29_39.parquet")
print(f"Columns: {df.columns.tolist()}")

Loading parquet data...
Columns: ['route', 'trip_id', 'stopid', 'thrusteet', 'hour', 'day_of_week', 'month', 'day_of_year', 'hour_sin', 'hour_cos', 'day_of_week_sin', 'day_of_week_cos', 'delay_seconds', 'Climate ID', 'Temp (°C)', 'Dew Point Temp (°C)', 'Rel Hum (%)', 'Wind Spd (km/h)', 'Visibility (km)', 'Stn Press (kPa)']

In [3]:
df.dtypes

route                         float64
trip_id                string[python]
stopid                 string[python]
thrusteet              string[python]
hour                          float64
day_of_week                   float64
month                         float64
day_of_year                   float64
hour_sin                      float64
hour_cos                      float64
day_of_week_sin               float64
day_of_week_cos               float64
delay_seconds                 float64
Climate ID                    float64
Temp (°C)                     float64
Dew Point Temp (°C)           float64
Rel Hum (%)                   float64
Wind Spd (km/h)               float64
Visibility (km)               float64
Stn Press (kPa)               float64
dtype: object

In [4]:
df_29 = df[df["route"] == 29]

In [5]:
df_29.isna().sum()

route                       0
trip_id                     0
stopid                      0
thrusteet              176437
hour                    40640
day_of_week             40640
month                   40640
day_of_year             40640
hour_sin                40640
hour_cos                40640
day_of_week_sin         40640
day_of_week_cos         40640
delay_seconds           40640
Climate ID                674
Temp (°C)                 674
Dew Point Temp (°C)       674
Rel Hum (%)               674
Wind Spd (km/h)           674
Visibility (km)           674
Stn Press (kPa)           674
dtype: int64

In [6]:
df_29[df_29.stopid.str.contains("_")].stopid.value_counts().sum()

np.int64(177373)

In [7]:
def create_bound(stopid):
    if "_" in stopid:
        get_bound = stopid.split("_")[1]
        return int(get_bound)
    else:
        return 0

df_29['bound'] = df_29['stopid'].apply(create_bound)

/tmp/ipykernel_15142/1413578387.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_29['bound'] = df_29['stopid'].apply(create_bound)

In [8]:
df_29[df_29.stopid.str.contains("_")].bound.value_counts().sum()

np.int64(177373)

In [9]:
df_29['stopid'] = df_29['stopid'].apply(lambda x: int(x.split("_")[0]) if "_" in x else int(x))

/tmp/ipykernel_15142/1405639651.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_29['stopid'] = df_29['stopid'].apply(lambda x: int(x.split("_")[0]) if "_" in x else int(x))

In [10]:
df_29.dtypes

route                         float64
trip_id                string[python]
stopid                          int64
thrusteet              string[python]
hour                          float64
day_of_week                   float64
month                         float64
day_of_year                   float64
hour_sin                      float64
hour_cos                      float64
day_of_week_sin               float64
day_of_week_cos               float64
delay_seconds                 float64
Climate ID                    float64
Temp (°C)                     float64
Dew Point Temp (°C)           float64
Rel Hum (%)                   float64
Wind Spd (km/h)               float64
Visibility (km)               float64
Stn Press (kPa)               float64
bound                           int64
dtype: object

In [11]:
df_29.isna().sum()

route                       0
trip_id                     0
stopid                      0
thrusteet              176437
hour                    40640
day_of_week             40640
month                   40640
day_of_year             40640
hour_sin                40640
hour_cos                40640
day_of_week_sin         40640
day_of_week_cos         40640
delay_seconds           40640
Climate ID                674
Temp (°C)                 674
Dew Point Temp (°C)       674
Rel Hum (%)               674
Wind Spd (km/h)           674
Visibility (km)           674
Stn Press (kPa)           674
bound                       0
dtype: int64

In [22]:
df_29_no_na = df_29.dropna(subset=['delay_seconds'])

In [23]:
df_29_no_na.isna().sum()

route                       0
trip_id                     0
stopid                      0
thrusteet              173185
hour                        0
day_of_week                 0
month                       0
day_of_year                 0
hour_sin                    0
hour_cos                    0
day_of_week_sin             0
day_of_week_cos             0
delay_seconds               0
Climate ID                674
Temp (°C)                 674
Dew Point Temp (°C)       674
Rel Hum (%)               674
Wind Spd (km/h)           674
Visibility (km)           674
Stn Press (kPa)           674
bound                       0
dtype: int64

In [31]:
df_29_no_na_dropped = df_29_no_na.dropna(subset=['Climate ID', 'thrusteet'])

In [32]:
df_29_no_na_dropped.shape

(4851443, 21)

In [33]:
df_29_no_na_filled = df_29_no_na.fillna(0)

In [34]:
df_29_no_na_filled.shape

(5025282, 21)

In [36]:
df_29_no_na_filled.head()

,route,trip_id,stopid,thrusteet,hour,day_of_week,month,day_of_year,hour_sin,hour_cos,...,day_of_week_cos,delay_seconds,Climate ID,Temp (°C),Dew Point Temp (°C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),bound
0,29.0,172354080,3880,Wilson Station,0.0,2.0,1.0,1.0,0.0,1.0,...,-0.222521,-40.000,6158731.0,1.6,1.6,100.0,27.0,16.1,97.93,0
1,29.0,52553080,2728,Princes' Gates Loop,0.0,2.0,1.0,1.0,0.0,1.0,...,-0.222521,-85.971,6158731.0,1.6,1.6,100.0,27.0,16.1,97.93,1
3,29.0,52553080,3993,Princes' Blvd,0.0,2.0,1.0,1.0,0.0,1.0,...,-0.222521,-5.855,6158731.0,1.6,1.6,100.0,27.0,16.1,97.93,0
4,29.0,52553080,34800,Princes' Blvd,0.0,2.0,1.0,1.0,0.0,1.0,...,-0.222521,28.000,6158731.0,1.6,1.6,100.0,27.0,16.1,97.93,0
6,29.0,172354080,1361,Dufferin St,0.0,2.0,1.0,1.0,0.0,1.0,...,-0.222521,29.027,6158731.0,1.6,1.6,100.0,27.0,16.1,97.93,0

In [38]:
df_29_no_na_filled = pd.get_dummies(df_29_no_na_filled, columns=['thrusteet'], prefix=['thrusteet'], dtype=int)

In [39]:
df_29_no_na_filled.head()

,route,trip_id,stopid,hour,day_of_week,month,day_of_year,hour_sin,hour_cos,day_of_week_sin,...,thrusteet_0,thrusteet_Dufferin St,thrusteet_Manitoba Dr,thrusteet_Nova Scotia Ave,thrusteet_Princes Blvd,thrusteet_Princes' Blvd,thrusteet_Princes' Gates Loop,thrusteet_Saskatchewan Rd,thrusteet_Wilson Ave,thrusteet_Wilson Station
0,29.0,172354080,3880,0.0,2.0,1.0,1.0,0.0,1.0,0.974928,...,0,0,0,0,0,0,0,0,0,1
1,29.0,52553080,2728,0.0,2.0,1.0,1.0,0.0,1.0,0.974928,...,0,0,0,0,0,0,1,0,0,0
3,29.0,52553080,3993,0.0,2.0,1.0,1.0,0.0,1.0,0.974928,...,0,0,0,0,0,1,0,0,0,0
4,29.0,52553080,34800,0.0,2.0,1.0,1.0,0.0,1.0,0.974928,...,0,0,0,0,0,1,0,0,0,0
6,29.0,172354080,1361,0.0,2.0,1.0,1.0,0.0,1.0,0.974928,...,0,1,0,0,0,0,0,0,0,0

In [40]:
df_29_no_na_filled.to_csv("./tmp/unfv_route_29_no_na_filled.csv", index=False)

In [41]:
df_29_no_na_dropped = pd.get_dummies(df_29_no_na_dropped, columns=['thrusteet'], prefix=['thrusteet'], dtype=int)

In [43]:
df_29_no_na_dropped.head(), df_29_no_na_dropped.shape

(   route    trip_id  stopid  hour  day_of_week  month  day_of_year  hour_sin  \
 0   29.0  172354080    3880   0.0          2.0    1.0          1.0       0.0
 1   29.0   52553080    2728   0.0          2.0    1.0          1.0       0.0
 3   29.0   52553080    3993   0.0          2.0    1.0          1.0       0.0
 4   29.0   52553080   34800   0.0          2.0    1.0          1.0       0.0
 6   29.0  172354080    1361   0.0          2.0    1.0          1.0       0.0

    hour_cos  day_of_week_sin  ...  bound  thrusteet_Dufferin St  \
 0       1.0         0.974928  ...      0                      0
 1       1.0         0.974928  ...      1                      0
 3       1.0         0.974928  ...      0                      0
 4       1.0         0.974928  ...      0                      0
 6       1.0         0.974928  ...      0                      1

    thrusteet_Manitoba Dr  thrusteet_Nova Scotia Ave  thrusteet_Princes Blvd  \
 0                      0                          0                       0
 1                      0                          0                       0
 3                      0                          0                       0
 4                      0                          0                       0
 6                      0                          0                       0

    thrusteet_Princes' Blvd  thrusteet_Princes' Gates Loop  \
 0                        0                              0
 1                        0                              1
 3                        1                              0
 4                        1                              0
 6                        0                              0

    thrusteet_Saskatchewan Rd  thrusteet_Wilson Ave  thrusteet_Wilson Station
 0                          0                     0                         1
 1                          0                     0                         0
 3                          0                     0                         0
 4                          0                     0                         0
 6                          0                     0                         0

 [5 rows x 29 columns],
 (4851443, 29))

In [44]:
df_29_no_na_dropped.to_csv("./tmp/unfv_route_29_no_na_dropped.csv", index=False)